version: "3.7"

networks:
    k6:
    influxdb:
    grafana:

services:

    grafana:
        restart: always
        image: grafana/grafana:latest
        networks:
            - grafana
            - influxdb
        ports:
            - "3000:3000"
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=false
            - GF_AUTH_BASIC_ENABLED=true
        volumes:
            - ./docker/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
            - ./docker/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
            - ./docker/grafana/k6-dashboard.json:/var/lib/grafana/dashboards/k6-dashboard.json

    influxdb:
        restart: always
        image: influxdb:latest
        networks:
            - k6
            - grafana
            - influxdb
        ports:
            - "8086:8086"
        environment:
            - INFLUXDB_DB=asmodeus

    k6:
        restart: always
        image: loadimpact/k6:latest
        networks:
            - k6
            - influxdb
        ports:
            - "6565:6565"
        environment:
            - K6_OUT=influxdb=http://influxdb:8086/asmodeus
        volumes:
            - ./scripts:/scripts
        command: "run /scripts/check.js --quiet --no-color"